# Generated by Django 4.1.4 on 2022-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='chield server ip', max_length=255)),
                ('label', models.CharField(default='chield server name', max_length=255)),
                ('version', models.CharField(default='chield server version', max_length=255)),
                ('last_connect', models.CharField(default='chield server version', max_length=255)),
                ('active', models.BooleanField(default='False')),
                ('active_host', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspectHost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(default='hostname', max_length=255)),
                ('host_in_lan', models.BooleanField(default='False')),
                ('agent_install', models.BooleanField(default='False')),
                ('agent_active', models.BooleanField(default='False')),
                ('instance_protect', models.BooleanField(default='False')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='base name', max_length=255)),
                ('date', models.CharField(default='base date', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
