# Generated by Django 4.1.4 on 2022-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('all_host', models.IntegerField(default=0)),
                ('active_host', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
