# Generated by Django 4.1.4 on 2022-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_mainserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='childserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mainserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suspecthost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
