# Generated by Django 4.1.4 on 2022-12-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_childserver_updated_at_mainserver_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childserver',
            old_name='updated_at',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='mainserver',
            old_name='updated_at',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='suspecthost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='updated_at',
        ),
    ]
