# Generated by Django 4.1.4 on 2022-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_childserver_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childserver',
            name='updated_at',
            field=models.CharField(default='2022-12-12T13:47:59+03:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainserver',
            name='updated_at',
            field=models.CharField(default='2022-12-12T13:47:59+03:00', max_length=255),
        ),
    ]
