# Generated by Django 4.1.4 on 2022-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_childserver_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childserver',
            name='updated_at',
            field=models.CharField(default='date', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainserver',
            name='updated_at',
            field=models.CharField(default='date', max_length=255),
        ),
    ]
